ifndef PREFIX
$(error "$$PREFIX must be set to esp8266 Core root directory")
endif

export ROOT = $(shell git rev-parse --show-toplevel)

export target = arduino
export DEFINE_TARGET = ARDUINO

export TOOLS ?= $(PREFIX)/tools/xtensa-lx106-elf/bin/xtensa-lx106-elf-
export SDK ?= $(PREFIX)/tools/sdk
export LIBS ?= $(PREFIX)/tools/sdk/lib

export LWIP_ROOT ?= $(ROOT)/lwip2-src

export LWIP_ESP ?= glue-esp/lwip-1.4-arduino/include
export BUILD_ROOT ?= $(ROOT)/build

TARGETS = liblwip2-536.a liblwip2-536-feat.a liblwip6-536-feat.a liblwip2-1460.a liblwip2-1460-feat.a liblwip6-1460-feat.a 
.PHONY: .prepare clean build install

include makefiles/Makefile.prepare-lwip2

.prepare: $(LWIP_ROOT)/.patched $(LWIP_ROOT)/.git/HEAD $(BUILD_ROOT)/lwip-err-t.h $(BUILD_ROOT)/lwip-git-hash.h

$(BUILD_ROOT)/liblwip2-536.a: .prepare
	$(MAKE) -f makefiles/Makefile.build-lwip2 \
		LWIP_LIB=$(@F) \
		BUILD=$(BUILD_ROOT)/build_$(@F) \
		TCP_MSS=536 \
		LWIP_FEATURES=0 \
		LWIP_IPV6=0 \
		all

$(BUILD_ROOT)/liblwip2-1460.a: .prepare
	@$(MAKE) -f makefiles/Makefile.build-lwip2 \
		LWIP_LIB=$(@F) \
		BUILD=$(BUILD_ROOT)/build_$(@F) \
		TCP_MSS=1460 \
		LWIP_FEATURES=0 \
		LWIP_IPV6=0 \
		all

$(BUILD_ROOT)/liblwip2-536-feat.a: .prepare
	@$(MAKE) -f makefiles/Makefile.build-lwip2 \
		LWIP_LIB=$(@F) \
		BUILD=$(BUILD_ROOT)/build_$(@F) \
		TCP_MSS=536 \
		LWIP_FEATURES=1 \
		LWIP_IPV6=0 \
		all

$(BUILD_ROOT)/liblwip2-1460-feat.a: .prepare
	@$(MAKE) -f makefiles/Makefile.build-lwip2 \
		LWIP_LIB=$(@F) \
		BUILD=$(BUILD_ROOT)/build_$(@F) \
		TCP_MSS=1460 \
		LWIP_FEATURES=1 \
		LWIP_IPV6=0 \
		all

$(BUILD_ROOT)/liblwip6-536-feat.a: .prepare
	@$(MAKE) -f makefiles/Makefile.build-lwip2 \
		LWIP_LIB=$(@F) \
		BUILD=$(BUILD_ROOT)/build_$(@F) \
		TCP_MSS=536 \
		LWIP_FEATURES=1 \
		LWIP_IPV6=1 \
		all

$(BUILD_ROOT)/liblwip6-1460-feat.a: .prepare
	@$(MAKE) -f makefiles/Makefile.build-lwip2 \
		LWIP_LIB=$(@F) \
		BUILD=$(BUILD_ROOT)/build_$(@F) \
		TCP_MSS=1460 \
		LWIP_FEATURES=1 \
		LWIP_IPV6=1 \
		all

BUILD_TARGETS = $(addprefix $(BUILD_ROOT)/,$(TARGETS))
INSTALL_TARGETS = $(addprefix $(LIBS)/,$(TARGETS))
$(INSTALL_TARGETS): $(BUILD_TARGETS)
	@cp -u $< $@

LWIP_INCLUDE = $(LWIP_ROOT)/src/include
BUILD_HEADERS = \
	$(LWIP_INCLUDE)/lwip/apps/sntp.h \
	$(wildcard $(LWIP_INCLUDE)/lwip/*.h)
INSTALL_HEADERS = \
	$(BUILD_HEADERS:$(LWIP_INCLUDE)=$(SDK)/lwip2/include)
$(INSTALL_HEADERS): $(BUILD_HEADERS)
	cp -u $< $@

build: $(BUILD_TARGETS)
install: $(INSTALL_TARGETS) $(INSTALL_HEADERS)

clean:
	rm -r $(BUILD_ROOT)

all: $(INSTALL_TARGETS)
