include makefiles/include/version.mk

GLUE_GIT_HEAD = $(ROOT)/.git/HEAD
LWIP_GIT_HEAD = $(LWIP_ROOT)/.git/HEAD

LWIP_GIT_REPO = https://github.com/lwip-tcpip/lwip

PATCHES = $(wildcard $(ROOT)/patches/*.patch)

$(BUILD_ROOT):
	@mkdir -p $(BUILD_ROOT)

$(LWIP_ROOT):
	mkdir -p $(LWIP_ROOT)
	git -C $(LWIP_ROOT) init
	git -C $(LWIP_ROOT) remote add origin $(LWIP_GIT_REPO)

$(LWIP_ROOT)/.patched: $(PATCHES) $(LWIP_ROOT)
	@for p in $(PATCHES); do \
		patch -d $(LWIP_ROOT) -p1 < $$p; \
	done
ifeq ($(target),open)
	patch -d $(LWIP_ROOT) -p1 < $(ROOT)/patches/open/sdk-mem-macros.patch
endif
	touch $@

$(LWIP_GIT_HEAD): makefiles/include/version.mk
	@git -C $(LWIP_ROOT) clean -f
	@git -C $(LWIP_ROOT) fetch origin $(UPSTREAM_VERSION)
	@git -C $(LWIP_ROOT) checkout -f $(UPSTREAM_VERSION)
	@touch $(LWIP_GIT_HEAD)

$(BUILD_ROOT)/lwip-err-t.h: $(LWIP_ESP)/arch/cc.h $(BUILD_ROOT)
	@/usr/bin/env bash makefiles/make-err-t $< > $@

$(BUILD_ROOT)/lwip-git-hash.h: $(GLUE_GIT_HEAD) $(LWIP_GIT_HEAD) $(BUILD_ROOT)
	@/usr/bin/env bash makefiles/make-lwip-hash $(LWIP_ROOT) > $@

all: $(BUILD_ROOT) $(LWIP_ROOT)/.patched $(BUILD_ROOT)/lwip-err-t.h $(BUILD_ROOT)/lwip-git-hash.h
