.PHONY: all

ifndef SDK
$(error SDK must point to our Core sdk folder)
endif

ifndef LWIP_ESP
$(error LWIP_ESP must point to espressif sdk lwip/include)
endif

SRC = $(wildcard glue-esp/*.c)

BUILD_INCLUDES = -I$(BUILD_ROOT) -I$(SDK)/include -I$(LWIP_ESP) -I$(ROOT)/glue
BUILD_FLAGS += -DLWIP14GLUE

include makefiles/include/defs.mk
include makefiles/include/rules.mk

-include $(BUILD)/glue-esp/*.d

all: $(OBJ)

$(OBJ): $(SRC) $(BUILD_ROOT)/user_config.h $(BUILD_ROOT)/lwip-err-t.h $(BUILD_ROOT)/lwip-git-hash.h
